(defun calculate-mean-pan (track)
  (let* ((left (snd-copy (aref track 0)))
         (right (snd-copy (aref track 1)))
         (sum 0.0)
         (count 0)
         (left-sample (snd-fetch left))
         (right-sample (snd-fetch right)))
    (while (and left-sample right-sample)
      (progn
        (let ((pan (calculate-pan-per-sample left-sample right-sample)))
          (when (and (numberp pan) (numberp left-sample) (numberp right-sample)
                     (/= left 0) (/= right 0))
            (setq sum (+ sum pan))
            (setq count (1+ count))))
        (setq left-sample (snd-fetch left))
        (setq right-sample (snd-fetch right))))
    (let ((mean-pan (if (> count 0)
                        (/ sum count)
                        0)))
      mean-pan)))

(defun find-pan-center (track)
  (let ((mean-pan (calculate-mean-pan track)))
    (let ((pan-value (round (* mean-pan 100))))
      pan-value)))

(find-pan-center *track*)
